import sys
src,dst=sys.argv[1],sys.argv[2]
h=open(src,encoding="utf-8").read()

NEW_CARD="  18:{city:'osaka',title:'Kinkaku-ji → Osaka',sub:'Golden Pavilion 10 AM · bags @ house ~2:15 · check-in 4 PM',badge:'move',badgeText:'BAGS ~2:15',tag:'🛏 House in Osaka — Nishinari-ku (Kishinosato Stn)',addr:'2-chōme-8-1 Shioji, Nishinari-ku, Osaka 557-0052',\n      chip:'⚠ This morning on hotel WiFi: message host 太田 Isamu — bag drop now ~2:15 (was 1:00)',\n      plan:['9:15 Loisir checkout — bags into Loisir storage (pickup ~12:15)','★ 9:30 🚕 2 taxis → Kinkaku-ji (~25–30 min · ~¥6,500–7,000 total)','★ 10:00–11:00 Kinkaku-ji (Golden Pavilion, ¥500) — one-way viewing path','📸 Crowd tactic: the money shot is the first pond viewpoint right after the entrance — it jams tight, but 20 steps further along the same bank the angle is nearly identical and half as packed. Take the photo there, then let the path carry you.','11:05 🚌 bus 205 southbound, Kinkakuji-michi → Kyoto Stn (~40 min · ¥230 IC, tap off at the front) · alt 🚕 2 cabs if the queue is long','11:50 🚶 to Loisir, collect bags → 12:20 🚕 to Kyoto Stn (~¥1,100 — don’t walk with the cases)','★ ~12:45–13:15 🚆 A-seat Special Rapid → Osaka Stn — car 9, reserved · rebook the ticketed 12:00 seats free via e5489 / green ticket machine · fallback: any ordinary Special Rapid, every ~7–8 min, ¥580 unreserved','13:50 🚕 2 cabs Osaka Stn → the Airbnb (~20–25 min · ~¥6,000) · show 西成区潮路2-8-1 · 🏷 host messaged: bag drop ~2:15 (moved from 1:00)','14:15 bags down → 🚇 Kishinosato → Namba (Yotsubashi line ~10 min)','★ 14:45–17:30 Kuromon Ichiba first (stalls close ~5–6 PM) → Dotonbori in daylight → Namba Yasaka if legs allow','~17:45 check in (4 PM+), settle','★ 19:00 Dotonbori by night — free-choice dinner: kushikatsu (Daruma), okonomiyaki, or a takoyaki crawl — pick by appetite on the strip'],\n      travel:[{f:'Loisir → Kinkaku-ji',d:'🚕 2 taxis ~25–30 min · ~¥6,500–7,000 total'},{f:'Kinkaku-ji → Kyoto Stn',d:'🚌 Bus 205 southbound from Kinkakuji-michi ~40 min · ¥230 IC, tap off · 🚕 2 cabs if the bus queue is long'},{f:'Loisir → Kyoto Stn (with bags)',d:'🚕 ~5 min · ~¥1,100 — don’t walk with the cases'},{f:'Kyoto → Osaka (A-seat)',d:'🚆 ~12:45–13:15 Special Rapid car 9, reserved · rebook the ticketed 12:00 seats free via e5489 or a green ticket machine · fallback: ordinary Special Rapid every ~7–8 min, ¥580 unreserved'},{f:'Osaka Stn → Airbnb',d:'🚕 2 cabs ~20–25 min · ~¥6,000 · show 西成区潮路2-8-1'},{f:'House → Namba',d:'🚇 Kishinosato → Namba · Yotsubashi line ~10 min · IC card'}],\n      total:{l:'Total',d:'Transport ~¥17–18k group today · tomorrow (Jul 19) is the free Osaka day · tap ⓘ'}},\n"
NEW_NOTES="18:{title:'Planning notes — Jul 18 (Kinkaku-ji morning + Osaka move)',body:[\n    'Kinkaku-ji moved to this morning: two taxis straight from Loisir (~25–30 min, ~¥6,500–7,000 total) put you at the gate for the 10:00 flow — it’s a one-way viewing path, so an hour covers it. Bags wait in Loisir storage (checkout 9:15, pickup ~12:15).',\n    'Back from the temple: bus 205 southbound from Kinkakuji-michi runs straight to Kyoto Stn (~40 min, ¥230, tap the IC card off at the front). If the stop queue looks long, two cabs beat it. Collect the bags at Loisir and take a short taxi to the station (~¥1,100) — don’t haul five cases the 12-minute walk in July heat.',\n    'The ticketed 12:00 A-seats no longer fit the morning — rebook the reserved car-9 seats FREE on e5489 (or any green ticket machine) to a ~12:45–13:15 departure. If rebooking is a hassle, ordinary Special Rapids run every ~7–8 min, ¥580 unreserved — just less luggage room.',\n    'Bag drop moved: ~2:15 at the Osaka house (was 1:00) to match the later train. ⚠ Message host 太田 Isamu to confirm before leaving the hotel WiFi this morning, and keep his number handy in the Go app. Fallback if plans shift: Namba coin lockers or ecbo cloak.',\n    'Money note: taxis do the heavy lifting today — transport lands around ¥17–18k for the group. Tomorrow (Jul 19) is the free Osaka day with almost no transit spend.',\n    KYOTO_BFAST\n  "
SIMPLE=[("18:{t:'The move to Osaka — bags dropped early at the house — then Japan’s brash food capital: Kuromon Ichiba market by day and Dotonbori’s neon canal by night.',q:'Dotonbori Osaka night'}", "18:{t:'Kinkaku-ji’s gold leaf in morning light, then the move to Osaka — Kuromon Ichiba market by day and Dotonbori’s neon canal by night.',q:'Dotonbori Osaka night'}"), ("18:['dotonbori']", "18:['kinkakuji','dotonbori']"), ('or, on Jul 18, a host-approved 1:00 PM early drop at the Osaka house.', 'or, on Jul 18, a ~2:15 PM early drop at the Osaka house (moved from 1:00 — host messaged).'), ('<tr><td class="prop">Jul 18</td><td>Kyoto → Osaka</td><td class="hide-sm">Out 11 · A-seat to Osaka · drop 1 PM</td><td><b>Bags → Airbnb direct</b>, host-approved 1:00 PM drop · fallback: Namba lockers / ecbo cloak if plans shift</td></tr>', '<tr><td class="prop">Jul 18</td><td>Kyoto → Osaka</td><td class="hide-sm">Out 9:15 · Loisir holds to ~12:15 · drop ~2:15</td><td><b>Bags → Loisir storage 9:15–12:15, then Airbnb direct</b>, drop ~2:15 (moved from 1:00) · fallback: Namba lockers / ecbo cloak if plans shift</td></tr>')]

i=h.find("  18:{city:'osaka'"); j=h.find("  19: OSAKA_FULL")
assert i>0 and j>i, "card markers not found"
h=h[:i]+NEW_CARD+h[j:]

i=h.find("18:{title:'Planning notes — Jul 18"); j=h.find("]},",i)
assert i>0 and j>i, "notes markers not found"
h=h[:i]+NEW_NOTES+h[j:]

for old,new in SIMPLE:
    n=h.count(old)
    assert n==1, "expected 1 occurrence, got %d for: %s..." % (n, old[:60])
    h=h.replace(old,new)

for must in ["Kinkaku-ji → Osaka","Crowd tactic","BAGS ~2:15","¥17–18k"]:
    assert must in h, "missing: "+must
for gone in ["Porta underground orbit","BAGS 1PM","host-approved 1:00"]:
    assert gone not in h, "leftover: "+gone

open(dst,"w",encoding="utf-8").write(h)
print("patch OK, %d chars" % len(h))
